### ISSUE TITLE
Support

### ISSUE THREAD

**Issue by mapyr** [koozil/Projekt_specki#1]
Szanowanko.

Potrzebujesz suportu w projekcie?
Chętnie coś dopiszę ^_^

**Comment by koozil** [comment]
Hmm... Wszelkie wsparcie jest  mile widziane :D
 1 kwi 2015 10:36 "Marcin Pyrka" notifications@github.com napisał(a):

**Comment by mapyr** [comment]
A co musisz mieć w finalnej wersji?

**Comment by koozil** [comment]
Tak na dobrą sprawę to może to być cokolwiek co będzie wykorzystywać PHP /
MySQL.
... Serio, cokolwiek :D
 1 kwi 2015 19:28 "Marcin Pyrka" notifications@github.com napisał(a):

**Comment by mapyr** [comment]
Może być baza danych kotów w schronisku?

**Comment by koozil** [comment]
A owszem. Świetny pomysł.  Dzięki wielkie ;)

**Comment by mapyr** [comment]
Powiedz mi tylko, czy używasz takiego narzędzia jak COMPOSER?

**Comment by koozil** [comment]
nope

**Comment by mapyr** [comment]
Kijowo... :(

**Comment by koozil** [comment]
Widać po kodzie...  To prosta sprawa jest. Ot co.
2 kwi 2015 00:10 "Marcin Pyrka" notifications@github.com napisał(a):

**Comment by mapyr** [comment]
Tak. Tylko nie ma co wyważać otwartych drzwi w tych czasach. 
Ale ok, rozumiem o co chodzi.

**Comment by mapyr** [comment]
Wszystko już wiem.
Pomyśl tylko co mieliście na zajęciach z MySQL'a cobyśmy za dużo nie zrobili.

**Comment by koozil** [comment]
Jeśli chodzi o MySQL to miałem absolutne minimum.  Czyli bez łączenia
strony z bazą. Dlatego teraz jest całkowita dowolność, bo jedyne co było
powiedziane to to, żeby była baza.
2 kwi 2015 13:39 "Marcin Pyrka" notifications@github.com napisał(a):

**Comment by mapyr** [comment]
Dziwnie jakoś.
Bez łączenia ale z bazą... Powiem Ci, że to skomplikowane...

czw., 2 kwi 2015, 14:58 Filip Kozłowski użytkownik notifications@github.com
napisał:

**Comment by koozil** [comment]
Nie miałem na lekcjach łączenia strony z bazą, ale teraz jest to wymagane.
(Źle się wysłowiłem + samo w sobie dziwnie to brzmi...)

**Comment by mapyr** [comment]
Szan. Na kiedy masz ten projekt? Bo jakoś czuję, że się zaraz szkoła kończy?

**Comment by koozil** [comment]
Easy.  Do 14ego
8 kwi 2015 13:15 "Marcin Pyrka" notifications@github.com napisał(a):

**Comment by mapyr** [comment]
6 dni? W zasadzie to 5? I kiedy chcesz nad tym usiąść?
